---
title: "Semana 9 - 5 casos"
author: "ANGULO CASTRO NAHOMI"
format: html
editor: visual
---

CASO 1

```{r}
#DATOS
x<-c(2,4,6,8,10)
y<-c(65,70,75,82,88)

#Correlación de pearsson
cor(x,y)

#Obtener coeficientes de la regresión
#Modelo
modelo <- lm(y ~ x)
coef(modelo)

#Hay una correlación fuerte positiva entre ambas variables

#Cuando recibe una capacitacion de 12 horas de duración
predict(modelo,data.frame(x=12))

#gráfico
plot(x,y,main = "Horas de capacitación vs Calidad de atención",
xlab="Horas de Capacitación",
ylab="Puntaje de Calidad",
pch=19)

abline(modelo,lwd=2)
```

CASO 2

```{r}
#DATOS
x<-c(1,2,3,4,5)
y<-c(60,68,75,82,90)

#Correlación de pearsson
cor(x,y)

#Obtener coeficientes de la regresión
#Modelo
modelo <- lm(y ~ x)
coef(modelo)

#Hay una correlación fuerte positiva entre ambas variables

#Cuando recibe una capacitacion de 12 horas de duración
predict(modelo,data.frame(x=6))

#gráfico
plot(x,y,main = "Horas de capacitación vs Calidad de atención",
xlab="Horas de Capacitación",
ylab="Puntaje de Calidad",
pch=19)

abline(modelo,lwd=2)
```

CASO 3

```{r}
#DATOS
x<-c(4,6,8,10,12)
y<-c(2,3,4,5,7)

#Correlación de pearsson
cor(x,y)

#Obtener coeficientes de la regresión
#Modelo
modelo <- lm(y ~ x)
coef(modelo)

#Hay una correlación fuerte positiva entre ambas variables

#Cuando recibe una capacitacion de 12 horas de duración
predict(modelo,data.frame(x=14))

#gráfico
plot(x,y,main = "Horas de capacitación vs Calidad de atención",
xlab="Horas de Capacitación",
ylab="Puntaje de Calidad",
pch=19)

abline(modelo,lwd=2)
```

CASO 4

```{r}
#DATOS
x<-c(1.0,1.5,2.0,2.5,3.0)
y<-c(145,142,138,134,130)

#Correlación de pearsson
cor(x,y)

#Obtener coeficientes de la regresión
#Modelo
modelo <- lm(y ~ x)
coef(modelo)

#Hay una correlación fuerte positiva entre ambas variables

#Cuando recibe una capacitacion de 12 horas de duración
predict(modelo,data.frame(x=3.5))

#gráfico
plot(x,y,main = "Horas de capacitación vs Calidad de atención",
xlab="Horas de Capacitación",
ylab="Puntaje de Calidad",
pch=19)

abline(modelo,lwd=2)
```

CASO 5

```{r}
#DATOS
x<-c(50,60,70,80,90)
y<-c(190,175,165,150,135)

#Correlación de pearsson
cor(x,y)

#Obtener coeficientes de la regresión
#Modelo
modelo <- lm(y ~ x)
coef(modelo)

#Hay una correlación fuerte positiva entre ambas variables

#Cuando recibe una capacitacion de 12 horas de duración
predict(modelo,data.frame(x=95))

#gráfico
plot(x,y,main = "Horas de capacitación vs Calidad de atención",
xlab="Horas de Capacitación",
ylab="Puntaje de Calidad",
pch=19)

abline(modelo,lwd=2)
```
